# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrant box for testing
Vagrant.configure("2") do |config|
  config.vm.box = "centos/stream10"
  memory = 8192
  cpus = 4

  config.vm.provider :virtualbox do |v, override|
    override.vm.box_url = "https://cloud.centos.org/centos/10-stream/x86_64/images/CentOS-Stream-Vagrant-10-latest.x86_64.vagrant-virtualbox.box"
    v.memory = memory
    v.cpus = cpus
  end

  config.vm.provider :libvirt do |v, override|
    override.vm.box_url = "https://cloud.centos.org/centos/10-stream/x86_64/images/CentOS-Stream-Vagrant-10-latest.x86_64.vagrant-libvirt.box"
    v.memory = memory
    v.cpus = cpus
  end

  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.provision "file", source: "../scripts", destination: "/tmp/provision"
  config.vm.provision "install packages", type: "shell", inline: "cd /tmp/provision && ./install-rpm.sh", run: "once"
  config.vm.provision "run tests", type: "shell", inline: "/tmp/provision/test.sh", run: "once"
end
