# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrant box for testing
Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu2204"
  memory = 6144
  cpus = 4

  config.vm.provider :virtualbox do |v|
    v.memory = memory
    v.cpus = cpus
  end

  config.vm.provider :libvirt do |v|
    v.memory = memory
    v.cpus = cpus
  end

  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.provision "file", source: "../scripts", destination: "/tmp/provision"
  config.vm.provision "install packages", type: "shell", inline: "cd /tmp/provision && ./install-deb.sh", run: "once"
  config.vm.provision "run tests", type: "shell", inline: "/tmp/provision/test.sh", run: "once"
end
