#!/usr/bin/env bash
set -euox pipefail

# Versions to be used
declare -A VERSIONS=(
    ["cni-plugins"]=v1.8.0
    ["conmon"]=v2.1.13
    ["conmon-rs"]=v0.7.3
    ["cri-tools"]=v1.34.0
    ["crun"]=1.25.1
    ["runc"]=v1.4.0
    ["crio-credential-provider"]=v0.1.2
)
export VERSIONS
