#!/usr/bin/env bash
set -euox pipefail

# Versions to be used
declare -A VERSIONS=(
    ["cni-plugins"]=v1.7.1
    ["conmon"]=v2.1.13
    ["conmon-rs"]=v0.7.1
    ["cri-tools"]=v1.33.0
    ["crun"]=1.22
    ["runc"]=v1.3.0
)
export VERSIONS
