#!/usr/bin/env bash
set -euox pipefail

curl -fsSL https://apt.releases.hashicorp.com/gpg | gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | tee /etc/apt/sources.list.d/hashicorp.list

# Fix the error: VirtualBox can't enable the AMD-V extension. Please disable
# the KVM kernel extension, recompile your kernel and reboot (VERR_SVM_IN_USE).
rmmod kvm_amd

apt-get update
apt-get install -y vagrant virtualbox
