#!/usr/bin/env bash
set -euo pipefail

set -x

retry_3() {
    for _ in 1 2 3; do
        if "$@"; then
            return
        else
            sleep 1
        fi
    done
    exit 1
}

curl_retry() {
    curl -sSfL --retry 5 --retry-delay 3 "$@"
}

install_osc() {
    OSC_VERSION=1.16.0
    # Because of https://github.com/openSUSE/osc/issues/1819 , ruamel.yaml should be installed separately
    sudo apt update -y && sudo apt install -y python3-ruamel.yaml
    curl_retry https://github.com/openSUSE/osc/archive/refs/tags/$OSC_VERSION.tar.gz -o- | tar xfz -
    pushd osc-$OSC_VERSION
    sudo ./setup.py build
    sudo ./setup.py install
    popd
}

install_krel() {
    KREL_VERSION=v0.18.0
    install_binary https://github.com/kubernetes/release/releases/download/$KREL_VERSION/krel-amd64-linux krel
}

install_bom() {
    BOM_VERSION=v0.6.0
    install_binary https://github.com/kubernetes-sigs/bom/releases/download/$BOM_VERSION/bom-amd64-linux bom
}

install_binary() {
    curl_retry "$1" -o "$2"
    chmod +x "$2"
    sudo cp "$2" /usr/local/bin
    rm "$2"
    "$2" version
}
