#!/usr/bin/env bash
set -euo pipefail

set -x

retry_3() {
    for _ in 1 2 3; do
        if "$@"; then
            return
        else
            sleep 1
        fi
    done
    exit 1
}

curl_retry() {
    curl -sSfL --retry 5 --retry-delay 3 "$@"
}

install_osc() {
    OSC_VERSION=1.8.3
    curl_retry https://github.com/openSUSE/osc/archive/refs/tags/$OSC_VERSION.tar.gz -o- | tar xfz -
    pushd osc-$OSC_VERSION
    sudo ./setup.py build
    sudo ./setup.py install
    popd
}

install_krel() {
    KREL_VERSION=v0.17.3
    BINARY=krel
    curl_retry https://storage.googleapis.com/k8s-artifacts-sig-release/kubernetes/release/$KREL_VERSION/$BINARY-amd64-linux -o $BINARY
    chmod +x $BINARY
    sudo cp $BINARY /usr/local/bin
    rm $BINARY
    $BINARY version
}
