#!/usr/bin/env bash
set -euo pipefail

curl_retry() {
    curl -sSfL --retry 5 --retry-delay 3 "$@"
}

install_osc() {
    OSC_VERSION=1.3.1
    curl_retry https://github.com/openSUSE/osc/archive/refs/tags/$OSC_VERSION.tar.gz -o- | tar xfz -
    pushd osc-$OSC_VERSION
    sudo ./setup.py build
    sudo ./setup.py install
    popd
}
