#!/usr/bin/env bash
set -euo pipefail

OBS_PASSWORD=${OBS_PASSWORD:-}

curl_retry() {
    curl -sSfL --retry 5 --retry-delay 3 "$@"
}

install_osc() {
    OSC_VERSION=1.3.1
    curl_retry https://github.com/openSUSE/osc/archive/refs/tags/$OSC_VERSION.tar.gz -o- | tar xfz -
    pushd osc-$OSC_VERSION
    sudo ./setup.py build
    sudo ./setup.py install
    popd

    printf "[general]\napiurl = https://api.opensuse.org\n[https://api.opensuse.org]\n" >~/.oscrc
    echo user=cri-o-release-bot >>~/.oscrc
    echo "pass=$OBS_PASSWORD" >>~/.oscrc
}

submit_workflow() {
    echo "Running GitHub OBS workflow for revision: $1"
    gh workflow run obs -F revision="$1"
}

install_osc

PACKAGES=$(osc se --package cri-o)
PROJECT_PREFIX=isv:kubernetes:addons:cri-o
PROJECT_PRERELEASE_PREFIX=$PROJECT_PREFIX:prerelease
BUILD_PROJECT_SUFFIX=:build/cri-o

echo "Iterating prerelease packages"
for PROJECT in $(echo "$PACKAGES" | grep "$PROJECT_PRERELEASE_PREFIX:.*:build.*cri-o" | tr -s '[:blank:]', '/'); do
    echo "Searching project: $PROJECT"
    VERSION=${PROJECT#"$PROJECT_PRERELEASE_PREFIX:"}
    VERSION=${VERSION%"$BUILD_PROJECT_SUFFIX"}

    BRANCH=main
    if [[ $VERSION =~ v.* ]]; then
        BRANCH=release-${VERSION#v}
    fi

    echo "Using branch: $BRANCH"
    submit_workflow "$BRANCH"

    RELEASE_PROJECT=${PROJECT%"$BUILD_PROJECT_SUFFIX"}
    echo "Cleanup old packages in: $RELEASE_PROJECT"
    mapfile -t RELEASE_PACKAGES < <(osc ls "$RELEASE_PROJECT")

    MAX_LEN=4
    if [[ ${#RELEASE_PACKAGES[@]} -ge $MAX_LEN ]]; then
        for ((i = 0; i < MAX_LEN; i++)); do
            unset 'RELEASE_PACKAGES[-1]'
        done
    fi

    echo "Keeping last $MAX_LEN packages in project $RELEASE_PROJECT, removing the rest"
    for PACKAGE in "${RELEASE_PACKAGES[@]}"; do
        osc rdelete -m cleanup "$RELEASE_PROJECT" "$PACKAGE"
    done
done

PREFIX=cri-o_
SUFFIX=.orig.tar.gz
PROJECT_STABLE_PREFIX=$PROJECT_PREFIX:stable

echo "Iterating stable packages"
for PROJECT in $(echo "$PACKAGES" | grep "$PROJECT_STABLE_PREFIX:.*:build.*cri-o" | tr -s '[:blank:]', '/'); do
    echo "Searching project: $PROJECT"
    VERSION=
    for FILE in $(osc ls "$PROJECT"); do
        if [[ $FILE =~ $PREFIX.*$SUFFIX ]]; then
            VERSION=${FILE#"$PREFIX"}
            VERSION=v${VERSION%"$SUFFIX"}
        fi
    done

    if [[ $VERSION == "" ]]; then
        VERSION=${PROJECT#"$PROJECT_STABLE_PREFIX:"}
        VERSION=${VERSION%"$BUILD_PROJECT_SUFFIX"}.0
        echo "No version found for project '$PROJECT', assuming $VERSION"
    else
        echo "Found latest OBS version '$VERSION' for project: $PROJECT"
    fi

    LATEST_VERSION=$(curl_retry "https://storage.googleapis.com/cri-o/latest-$(echo "$VERSION" | cut -c2-5).txt" || echo -n "")
    if [[ "$LATEST_VERSION" == "" ]]; then
        echo "No latest release found for OBS version '$VERSION'"
    elif [[ "$LATEST_VERSION" != "$VERSION" ]]; then
        echo "Latest release version '$LATEST_VERSION' is not matching OBS latest version '$VERSION'"
        submit_workflow "$LATEST_VERSION"
    else
        echo "Latest release '$LATEST_VERSION' already available in project: $PROJECT"
    fi
done
