#!/usr/bin/env bash

source "$(dirname "${BASH_SOURCE[0]}")"/helpers

BUNDLE_DIR=${ARCHIVE_PATH:-build/bundle}

sign_blob() {
    echo "Signing $1"
    cosign sign-blob -y "$1" \
        --bundle "$1.bundle" \
        --output-signature "$1.sig" \
        --output-certificate "$1.cert"
}

for ARTIFACT in "$BUNDLE_DIR"/*.tar.gz "$BUNDLE_DIR"/*.tar.gz.sha256sum \
    "$BUNDLE_DIR"/*.tar.gz.spdx.json "$BUNDLE_DIR"/*.openvex.json \
    "$BUNDLE_DIR"/*.provenance.json; do
    [[ -e "$ARTIFACT" ]] || continue
    sign_blob "$ARTIFACT"
done
