#!/usr/bin/env bash

source "$(dirname "${BASH_SOURCE[0]}")"/helpers

for TARBALL in build/bundle/*.tar.gz; do
    cosign sign-blob -y "$TARBALL" \
        --bundle "$TARBALL.bundle" \
        --output-signature "$TARBALL.sig" \
        --output-certificate "$TARBALL.cert"
done

for SBOM in build/bundle/*.tar.gz.spdx; do
    cosign sign-blob -y "$SBOM" \
        --bundle "$SBOM.bundle" \
        --output-signature "$SBOM.sig" \
        --output-certificate "$SBOM.cert"
done

for VEX in build/bundle/*.openvex.json; do
    [[ -e "$VEX" ]] || continue
    cosign sign-blob -y "$VEX" \
        --bundle "$VEX.bundle" \
        --output-signature "$VEX.sig" \
        --output-certificate "$VEX.cert"
done

for PROVENANCE in build/bundle/*.provenance.json; do
    [[ -e "$PROVENANCE" ]] || continue
    cosign sign-blob -y "$PROVENANCE" \
        --bundle "$PROVENANCE.bundle" \
        --output-signature "$PROVENANCE.sig" \
        --output-certificate "$PROVENANCE.cert"
done
