#!/usr/bin/env bash
set -euox pipefail

source "$(dirname "${BASH_SOURCE[0]}")"/vars

TYPE=${TYPE:-}
TESTDIR="test/$TYPE"

if [[ $TYPE == "" ]]; then
    echo "TYPE is not set"
    exit 1
fi

if [ "$(uname)" == "Darwin" ]; then
    PATH="/usr/local/opt/gnu-sed/libexec/gnubin:$PATH"
    SED=gsed
else
    SED=sed
fi

$SED -i 's;PROJECT_PATH=.*;PROJECT_PATH='"$PROJECT_TYPE:/$PROJECT_VERSION"';g' "$TESTDIR/Vagrantfile"
pushd "$TESTDIR"
vagrant up
