#!/usr/bin/env bash
set -euox pipefail

source "$(dirname "${BASH_SOURCE[0]}")"/vars

TYPE=${TYPE:-}
TESTDIR="test/$TYPE"

if [[ $TYPE == "" ]]; then
    echo "TYPE is not set"
    exit 1
fi

pushd "$TESTDIR"
echo "PROJECT_PATH=$PROJECT_TYPE:/$PROJECT_VERSION" >"env"
vagrant up
