#!/usr/bin/env bash

source "$(dirname "${BASH_SOURCE[0]}")"/helpers

BUNDLE_DIR=${ARCHIVE_PATH:-build/bundle}

IDENTITY="https://github.com/cri-o/packaging/.github/workflows/obs.yml@.*"
ISSUER=https://token.actions.githubusercontent.com

verify_blob() {
    echo "Verifying $1"
    cosign verify-blob "$1" \
        --certificate-identity-regexp "$IDENTITY" \
        --certificate-oidc-issuer "$ISSUER" \
        --certificate-github-workflow-repository cri-o/packaging \
        --bundle "$1.bundle"
}

for ARTIFACT in "$BUNDLE_DIR"/*.tar.gz "$BUNDLE_DIR"/*.tar.gz.sha256sum \
    "$BUNDLE_DIR"/*.tar.gz.spdx.json "$BUNDLE_DIR"/*.openvex.json \
    "$BUNDLE_DIR"/*.provenance.json; do
    [[ -e "$ARTIFACT" ]] || continue
    verify_blob "$ARTIFACT"
done
