name: test
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - run: make verify-dependencies

  shfmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - run: make verify-shfmt

  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - run: make verify-shellcheck

  get-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - run: sudo ./get
      - run: crio version

  get-script-with-verification:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: sigstore/cosign-installer@fb28c2b6339dcd94da6e4cbcbc5e888961f6f8c3 # v3.9.0
      - run: make verify-get-script
      - name: Install BOM
        run: |
          BOM_VERSION=v0.6.0
          curl -sSfL --retry 5 --retry-delay 3 -o bom \
            https://github.com/kubernetes-sigs/bom/releases/download/$BOM_VERSION/bom-amd64-linux
          chmod +x bom
          sudo cp bom /usr/bin
      - run: sudo -E PATH=$PATH ./get
      - run: crio version

  mdtoc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - run: make verify-mdtoc

  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: creyD/prettier_action@5e54c689403b43aac746a34c07656fd4cb71d822 # v4.5
        with:
          dry: true
          prettier_options: --write .
