name: test
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - run: make verify-dependencies

  shfmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - run: make verify-shfmt

  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - run: make verify-shellcheck

  get-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - run: sudo ./get
      - run: crio version

  get-script-with-verification:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - uses: sigstore/cosign-installer@59acb6260d9c0ba8f4a2f9d9b48431a222b68e20 # v3.5.0
      - run: make verify-get-script
      - name: Install BOM
        run: |
          BOM_VERSION=v0.6.0
          curl -sSfL --retry 5 --retry-delay 3 -o bom \
            https://github.com/kubernetes-sigs/bom/releases/download/$BOM_VERSION/bom-amd64-linux
          chmod +x bom
          sudo cp bom /usr/bin
      - run: sudo -E PATH=$PATH ./get
      - run: crio version
